version: '3.1'

services:
  mk_appointment_postgres:
    image: postgres:9.6-alpine
    volumes:
      - mk_appointment_postgres_data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: mk_appointment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    container_name: mk_appointment_postgres

volumes:
  mk_appointment_postgres_data:
    driver: local